//! The server this loader was built for.
//!
//! Generated by `build.rs` from `.env` or the environment; see `.env.example`.
//! Nothing here reaches the interface — the player is never shown an address
//! or a key, and cannot change either.

include!(concat!(env!("OUT_DIR"), "/pinned.rs"));

use ds2os_core::InjectorConfig;

/// Login port. Fixed because the injector patches the retail port too and the
/// server's own default matches.
pub const SERVER_PORT: i32 = 50050;

/// The configuration the injector reads, with every gameplay patch on.
///
/// None of this is a user setting. The three area hooks are indivisible
/// behind `DS2ForceMultiPlayZone`, and the phantom timer has to stay above
/// 900: the hook only writes when the running value is *below* the target, so
/// a smaller number is a silent no-op that looks like a broken patch.
pub fn injector_config() -> InjectorConfig {
    InjectorConfig {
        ServerName: SERVER_NAME.to_owned(),
        ServerHostname: SERVER_HOST.to_owned(),
        ServerPublicKey: SERVER_KEY.to_owned(),
        ServerGameType: "DarkSouls2".to_owned(),
        ServerPort: SERVER_PORT,
        EnableSeperateSaveFiles: true,

        DS2ForceMultiPlayZone: true,
        // The barrier that pens a phantom into the host's area. Measured in
        // Heide: it does not appear, both players move freely, and boss gates
        // still work. One area and one pair of players is what that rests on.
        DS2RemovePhantomFog: true,
        DS2ForcedZoneId: 103110,
        DS2PatchPhantomTimers: true,
        DS2PhantomTimerSeconds: 4000.0,

        DS2ProbeArea: false,
        DS2WatchAreaReads: false,
        DS2AreaAddress: String::new(),
        DS2ProbeMultiPlayZone: false,
    }
}
