//! Preparing a Proton launch.
//!
//! Strategy: the game keeps being started by Steam, but Steam is pointed at a
//! wrapper script through the game's launch options. The wrapper swaps the game
//! executable in Proton's command line for `Injector.exe`, which then starts the
//! game itself and injects `Injector.dll` exactly the way the Windows loader
//! does.
//!
//! Going through `%command%` rather than invoking `proton run` separately is the
//! whole point: the injector then runs inside the same pressure-vessel container
//! and the same wineserver session as the game. Anything launched from outside
//! would land in neither.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::config::InjectorConfig;
use crate::steam::GameInstall;

/// Files the loader drops next to the game executable.
pub const INJECTOR_DLL: &str = "Injector.dll";
pub const INJECTOR_EXE: &str = "Injector.exe";
pub const WRAPPER_SCRIPT: &str = "ds2os-launch.sh";

#[derive(Debug, thiserror::Error)]
pub enum LaunchError {
    #[error("Steam has not created a Proton prefix yet; run the game once through Steam first")]
    NoPrefix,
    #[error("{0} is missing; build it and point the loader at its directory")]
    MissingInjector(PathBuf),
    #[error("failed to write {path}: {source}")]
    Write { path: PathBuf, source: std::io::Error },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LaunchPlan {
    /// Line the user pastes into the game's Steam launch options.
    pub launch_options: String,
    pub script_path: PathBuf,
    pub injector_config_path: PathBuf,
}

/// Writes the injector config and the wrapper script, and returns the launch
/// options line for Steam.
///
/// `injector_source` is the directory holding the Windows-built `Injector.dll`
/// and `Injector.exe`; both are copied next to the game so the injector finds
/// its config as `<dll directory>/Injector.config`.
pub fn prepare(
    install: &GameInstall,
    config: &InjectorConfig,
    injector_source: &Path,
) -> Result<LaunchPlan, LaunchError> {
    if install.prefix_path.is_none() {
        return Err(LaunchError::NoPrefix);
    }

    // Both are required: the exe performs the injection and the dll is what it
    // injects. Neither is useful alone.
    let game_dir = &install.install_dir;
    for name in [INJECTOR_DLL, INJECTOR_EXE] {
        let source = injector_source.join(name);
        if !source.is_file() {
            return Err(LaunchError::MissingInjector(source));
        }
        copy_into(&source, &game_dir.join(name))?;
    }

    let injector_config_path = config
        .write_to(game_dir)
        .map_err(|source| LaunchError::Write { path: game_dir.join("Injector.config"), source })?;

    let script_path = game_dir.join(WRAPPER_SCRIPT);
    let script = wrapper_script(install.game_type.executable());
    write_executable(&script_path, &script)?;

    Ok(LaunchPlan {
        launch_options: format!("{} %command%", shell_quote(&script_path)),
        script_path,
        injector_config_path,
    })
}

/// The wrapper Steam runs in place of the game.
fn wrapper_script(game_exe: &str) -> String {
    format!(
        r#"#!/usr/bin/env bash
# Generated by the ds2os loader. Regenerated on every launch; do not edit.
#
# Steam calls this with Proton's full command line, whose last argument is the
# game executable. We swap that for Injector.exe and hand it the real
# executable, so the injector runs inside the same container and wineserver
# session as the game.
set -euo pipefail

game_exe_name="{game_exe}"
here="$(cd -- "$(dirname -- "${{BASH_SOURCE[0]}}")" && pwd)"
injector="$here/Injector.exe"

args=("$@")
last=$((${{#args[@]}} - 1))

if [[ ! -f "$injector" ]]; then
  echo "ds2os: $injector is missing; starting the game unmodified" >&2
  exec "${{args[@]}}"
fi

if [[ "${{args[$last]}}" != *"$game_exe_name" ]]; then
  echo "ds2os: last argument is not $game_exe_name; starting the game unmodified" >&2
  exec "${{args[@]}}"
fi

game="${{args[$last]}}"
args[$last]="$injector"
args+=("$game")

exec "${{args[@]}}"
"#
    )
}

fn copy_into(source: &Path, destination: &Path) -> Result<(), LaunchError> {
    std::fs::copy(source, destination)
        .map(|_| ())
        .map_err(|error| LaunchError::Write { path: destination.to_path_buf(), source: error })
}

fn write_executable(path: &Path, contents: &str) -> Result<(), LaunchError> {
    std::fs::write(path, contents)
        .map_err(|source| LaunchError::Write { path: path.to_path_buf(), source })?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755))
            .map_err(|source| LaunchError::Write { path: path.to_path_buf(), source })?;
    }

    Ok(())
}

/// Quotes a path for a Steam launch options line, which is parsed by a shell.
fn shell_quote(path: &Path) -> String {
    let text = path.to_string_lossy();
    if text.chars().all(|c| c.is_ascii_alphanumeric() || "._-/".contains(c)) {
        text.into_owned()
    } else {
        format!("'{}'", text.replace('\'', r"'\''"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quotes_only_when_needed() {
        assert_eq!(shell_quote(Path::new("/home/u/game/run.sh")), "/home/u/game/run.sh");
        assert_eq!(
            shell_quote(Path::new("/home/u/My Games/run.sh")),
            "'/home/u/My Games/run.sh'"
        );
        assert_eq!(shell_quote(Path::new("/it's/run.sh")), r"'/it'\''s/run.sh'");
    }

    #[test]
    fn wrapper_falls_back_instead_of_failing() {
        let script = wrapper_script("DarkSoulsII.exe");
        // Both guards must exec the original command rather than abort, so a
        // broken install still starts the game.
        assert_eq!(script.matches(r#"exec "${args[@]}""#).count(), 3);
        assert!(script.contains("DarkSoulsII.exe"));
    }
}
